#!/bin/bash

# Check if required environment variables are set
if [ -z "$MY_PASSWORD" ] || [ -z "$MY_USER" ]; then
    echo "Error: MY_PASSWORD and MY_USER must be set before running this script."
    exit 1
fi

# Check for window manager argument
if [ "$1" != "dwm" ] && [ "$1" != "i3" ]; then
    echo "Error: Please specify 'dwm' or 'i3' as an argument."
    echo "Usage: $0 [dwm|i3]"
    exit 1
fi

WM_CHOICE="$1"

# Improved error handling function
handle_error() {
    local line_content=$(sed -n "${LINENO}p" "$0")
    echo "An error occurred at line $LINENO: $line_content. Exiting..." >&2
    exit 1
}

# Setup a trap to catch errors and execute handle_error function
trap 'handle_error $LINENO' ERR

# Update package database and install necessary packages
pacman -Sy
pacman -S --noconfirm --needed archlinux-keyring python archinstall git

# Clone dotfiles repository
git clone https://github.com/nhkduy201/dotfiles

# Update user credentials in the configuration file
sed -i "s/\"!root-password\": \"password\"/\"!root-password\": \"$MY_PASSWORD\"/" dotfiles/user_credentials.json
sed -i "s/\"!password\": \"password\"/\"!password\": \"$MY_PASSWORD\"/" dotfiles/user_credentials.json

# Run archinstall with the provided configuration and credentials
if ! archinstall --config dotfiles/user_configuration.json --creds dotfiles/user_credentials.json --silent; then
    echo "Error: archinstall failed. Check the logs for more information."
    exit 1
fi

# Save SSID and passphrase
mkdir -p /mnt/archinstall/home/$MY_USER
mv dotfiles /mnt/archinstall/home/$MY_USER
iwctl station wlan0 show | grep 'Connected network' | sed 's/.*Connected network\s*//' > /mnt/archinstall/home/$MY_USER/wifi_ssid
SSID=$(cat /mnt/archinstall/home/$MY_USER/wifi_ssid)
grep Passphrase "/var/lib/iwd/${SSID}.psk" | sed 's/.*Passphrase=//' > /mnt/archinstall/home/$MY_USER/wifi_password

# Create the one-time systemd service
cat <<EOF > /mnt/archinstall/etc/systemd/system/$MY_USER-post-install.service
[Unit]
Description=$MY_USER post install
After=network-online.target
Wants=network-online.target
Before=getty@tty1.service

[Service]
Type=oneshot
User=$MY_USER
Group=$MY_USER
WorkingDirectory=/home/$MY_USER/dotfiles
ExecStart=/usr/bin/sudo /home/$MY_USER/dotfiles/post_install -a $WM_CHOICE
ExecStartPost=/usr/bin/systemctl disable $MY_USER-post-install.service
StandardOutput=journal+console
StandardError=journal+console

[Install]
WantedBy=multi-user.target
EOF

# Enable the one-time systemd service
arch-chroot /mnt/archinstall systemctl enable $MY_USER-post-install.service

# Correctly add a sudoers rule
arch-chroot /mnt/archinstall bash -c "echo \"$MY_USER ALL=(ALL) NOPASSWD: ALL\" | tee /etc/sudoers.d/00_nopasswd"

# Change ownership
arch-chroot /mnt/archinstall bash -c "chown -R $MY_USER:$MY_USER /home/$MY_USER/"

# Reboot the system
reboot
