#!/bin/bash

# pacman -Sy
# pacman -S --noconfirm archlinux-keyring
# pacman -S --noconfirm archinstall git
# git clone https://github.com/nhkduy201/dotfiles
# archinstall --config dotfiles/user_configuration.json --creds dotfiles/user_credentials.json --silent
# cp -r dotfiles /mnt/archinstall/home/kayd
# arch-chroot /mnt/archinstall /bin/bash -c "su kayd -c 'cd /home/kayd/dotfiles && sudo ./post_install -a && exit'"
# reboot

pacman -Sy
pacman -S --noconfirm archlinux-keyring python archinstall git
git clone https://github.com/nhkduy201/dotfiles
sed -i "s/\"!root-password\": \"password\"/\"!root-password\": \"$PASSWORD\"/" dotfiles/user_credentials.json
sed -i "s/\"!password\": \"password\"/\"!password\": \"$PASSWORD\"/" dotfiles/user_credentials.json
archinstall --config dotfiles/user_configuration.json --creds dotfiles/user_credentials.json --silent

# mkdir -p /mnt/archinstall/home/kayd
# cp -r dotfiles /mnt/archinstall/home/kayd/
# arch-chroot /mnt/archinstall /bin/bash -c "chown -R kayd:kayd /home/kayd/dotfiles && su kayd -c 'cd /home/kayd/dotfiles && sudo ./post_install -a && exit'"

# Create the one-time systemd service
cat <<EOF > /etc/systemd/system/one-time-command.service
[Unit]
Description=Run a one-time command after reboot

[Service]
Type=oneshot
WorkingDirectory=/home/kayd/dotfiles
ExecStart=/usr/bin/sudo /bin/bash /home/kayd/dotfiles/post_install -a
ExecStartPost=/bin/sh -c 'rm -f /etc/systemd/system/one-time-command.service && systemctl daemon-reload'

[Install]
WantedBy=multi-user.target
EOF

# Enable the one-time command service
systemctl enable one-time-command.service

reboot
